### ISSUE TITLE
openreview-py should support python 3

### ISSUE THREAD

**Issue by zbialecki** [iesl/openreview-py#118]
Importing the module in a python 3 environment throws the following error:
```
>>> import openreview
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.6/site-packages/openreview/__init__.py", line 2, in <module> 
  from tools import *
ModuleNotFoundError: No module named 'tools'
```
This error is related to the use of relative imports which are no longer allowed in python: https://wiki.python.org/moin/PortingPythonToPy3k#relative-imports

**Comment by mspector** [comment]
thanks @zbialecki, this is in the works
